// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zczaicsmeazucvsihick.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjemFpY3NtZWF6dWN2c2loaWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMxMzA1ODEsImV4cCI6MjA3ODcwNjU4MX0.kF4gELeabRcFkVGuFeA0gHjvm-in2O-eM36EGrJNM64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});